### ISSUE TITLE
Create Token and Pool: Program Error: "The Program Expected This Account To Be Already Initialized"

### ISSUE THREAD

**Issue by mishanefedov** [memechan-gg/memechan-sol-sdk#212]
Hello,

I am trying to create a token and pool, but I get [Program Error: "The Program Expected This Account To Be Already Initialized"].

I have tried both [create-toke-and-pool.ts](https://github.com/memechan-gg/memechan-sol-sdk/blob/main/examples/bonding-pool/create/create-new-token-and-pool.ts) and [create-token-and-pool-tx.ts](https://github.com/memechan-gg/memechan-sol-sdk/blob/main/examples/bonding-pool/create/create-new-token-and-pool-tx.ts) scripts, but they both result in the same error.
The Test Wallet has SOL.

This is one of the transactions: https://solscan.io/tx/51fyWMgw2Bd5ozmKNU2fUJvhL6E1hC2LzmjoZAG9NpyBUGd5RkYtxEyz8fL1QU11yYsczF6PbLuXrMiDyni1s2Ab

What can be the reason for this error?

**Comment by 0xunreal** [comment]
Hey,

please use the v2 examples, the others are considered deprecated now - we will mark them so soon.

These, that support the current token creation flows from the site:

https://github.com/memechan-gg/memechan-sol-sdk/blob/main/examples/v2/bonding-pool/create/create-new-token-and-pool-from-be-tx.ts

https://github.com/memechan-gg/memechan-sol-sdk/blob/main/examples/v2/bonding-pool/create/create-new-token-and-pool-on-be.ts
